### ISSUE TITLE
Simplify `relation` field type

### ISSUE THREAD

**Issue by adzialocha** [p2panda/p2panda#229]
## Current situation

```yaml
field:
  type: relation
  value:
    document: <document_id>
    document_view: [<operation id>, <operation id>, ...] # Is optional and only used for pinned relations

field:
  type: relation_list
  value:
    - document: <document_id>
      document_view: [<operation id>, <operation id>, ...]
    - ..
```

## Suggestion

**Relation** is a document id

```yaml
field:
  type: relation
  value: <document id>
```

**Pinned relation** is a document view id (basically skipping the document id for pinned relations)

```yaml
field:
  type: relation
  value: [<operation id>, <operation id>, ...]
```

**Relation list** is a list of document ids

```yaml
field:
  type: relation_list
  value: [<document id>, ...]
```

**Pinned relation list** is a list of document view ids

```yaml
field:
  type: relation_list
  value: [[<operation id>, <operation id>, ...], [<operation_id>, ...], ...]
```
