### ISSUE TITLE
Make `SchemaId::Application` value a `PinnedRelation` type

### ISSUE THREAD

**Issue by adzialocha** [p2panda/p2panda#245]
```yaml
action: update | create | delete
version: 1
schema: [<operation id>, ...] # This will be a pinned relation
fields: ...
```
