### ISSUE TITLE
Let schemas carry a prescribed schema for relation fields

### ISSUE THREAD

**Issue by cafca** [p2panda/p2panda#264]
Documents referenced by relation fields must conform to the same schema. Therefore, our `Schema` struct should record this information.

**Comment by adzialocha** [comment]
Ah cool! This is about any relation also prescribing a schema for the referred document, right? Will it be something like this?

```yaml
...
schema: "schema_field_definition_v1"
fields:
  name:
    type: "str"
    value: "Profiles"
  schema:  // <-- Is it this here?
    type: "pinned_relation"
    value: [...]
```

**Comment by sandreae** [comment]
@cafca has a slightly different plan, but it isn't that different to what you suggest. Think it'll be passed into `FieldType` relation variants and then handled in the cddl definition generator.

**Comment by sandreae** [comment]
We discussed doing it how you suggested too, either way would be good :+1:

**Comment by adzialocha** [comment]
> @cafca has a slightly different plan, but it isn't that different to what you suggest. Think it'll be passed into `FieldType` relation variants and then handled in the cddl definition generator.

Do you have an example? How does the schema creator decide what schema should be followed in the referrenced documents?

**Comment by sandreae** [comment]
I should let @cafca share an example ;-p

**Comment by cafca** [comment]
Yes, what you wrote @adzialocha is an option definitely. The other thought I had was that in our sketches, etc, we have often been writing relations to a schema using shorthand such as:

```yaml
relation(venue)
```

I thought it could be nice to use this notation also for schema field definitions. This would work nicely together with #267 to produce something like

```
action: create
version: 1
schema: "schema_field_definition_v1"
fields:
  name:
    type: "str"
    value: "profile"
  type: 
    type: "str"
    value: "pinned_relation(venue_11df58403d1802597484f5cd862fef21164135d2508ac9b494c4d32b)"
```

But this has the downside that we now have to parse this identifier using e.g. regex instead of just being able to read it, so maybe the other way is actually nicer.
